#+title: Pour une politique d'utilisation et de publication des logiciels libres dans le secteur public

* Idées en vrac

- Construire un positionnement et un discours clairs sur le rapport
  entre l'ouverture des codes sources publics et la souveraineté
  numérique.

- En s'inspirant du réseau des Administrateurs Ministériels de Données
  (AMD), construire un réseau interministériel de référents logiciels
  libres dans les ministères.

- Mettre en place un baromètre de l'open source pour l'administration.

- Aider les Société d'Accélération de Transfert de Technologies ([[https://www.satt.fr/societe-acceleration-transfert-technologies/][SATT]])
  à mieux comprendre les modèles économiques qui peuvent être proposés
  autour de logiciels libres.

- Mettre en place une politique industrielle venant en soutien aux
  entreprises du logiciels libres en France.

- Mettre en place la priorité à l'utilisation de logiciels libres dans
  le secteur public français, comme c'est le cas en Italie.

- Soutenir la montée en compétence des services juridiques et achat
  des administrations publiques pour qu'elles appréhendent mieux les
  enjeux du logiciel libre.

- Encourager le secteur de la l'enseignement supérieur et recherche à
  détecter et soutenir les futures « pépites » libres développées sur
  fonds publics (e.g. [[https://scikit-learn.org][scikit-learn]]).

- Mettre en place un portail unique pour toutes les publications liées
  à l'open source dans la sphère publique.

- Tenir une liste à jour des organismes publics ayant une politique
  d'utilisation et de publication de logiciels libres.

- "Financer le déploiement, la maintenance et les évolutions
  d'instances de frama* et autres services libres au service de
  l'administration et des citoyens, notamment outils « transverses »
  (ex: matomo, sentry, captchas, nextcloud...) Et sensibiliser à
  l'utilisation de ces services." ([[https://twitter.com/revolunet/status/1284129025074626560][via Twitter]])

- "Monter une équipe degafamisation à la DINUM pour éradiquer les
  trackers dans les outils de l'état, former et sensibiliser les
  équipes internes aux alernatives libres" ([[https://twitter.com/revolunet/status/1284129545357086722][via Twitter]])

- Organiser des formations professionnelles autour des logiciels
  libres ([[https://twitter.com/sebtouze/status/1284383159036059649][ce tweet]]) et notamment "former les DSI des établissements
  publics sur les logiciels libres (qu'ils n'en aient pas peur)"
  (cf. [[https://twitter.com/thom_karum/status/1284189815483899911][ce tweet]]).

- "Valoriser les exemples réussis, mettre en réseau, partager les
  bonnes pratiques et faire des guides simples pour rassurer sur les
  aspects juridiques et les modes de gouvernance." ([[https://twitter.com/cmonchicourt/status/1284833611502571522][via Twitter]])

- "Faire en sorte que chacune des applications developpées avec des
  fonds publics soit pensée comme un outil libre (documenté,
  réutilisable, reinstallable, partiellement générique) au lieu d’une
  simple ouverture du code." ([[https://twitter.com/jparis_py/status/1284606997573390339][via Twitter]])

- "Une infra numérique libre et décentralisée ?" ([[https://twitter.com/jparis_py/status/1284606997573390339][via Twitter]])

- "Montrer et démontrer les avantages et bénéfices du code source
  libre et de la gouvernance ouverte" ([[https://twitter.com/nyconyco/status/1284115111263850501][via Twitter]])

- Acculturer les ESN à l'open source pour les inciter à répondre aux
  exigences de l'administration lorsqu'elle souhaite éviter la
  dépendance aux GAFAM (inspiré de [[https://twitter.com/pgayat/status/1284437480234770432][ce tweet]]).

- Collecter et publier des témoignages d'utilisations et transitions
  réussies (inspiré de [[https://twitter.com/drobaux/status/1284451842768896004][ce tweet]]).

- Publier de la documentation (notamment vidéo) autour des logiciels
  libres (inspiré de [[https://twitter.com/drobaux/status/1284451842768896004][ce tweet]]).

- "Organiser des install parties [dans l'administration]" (via
  [[https://twitter.com/looking4poetry/status/1284118404950110208][Twitter]])

- "choisir des early-adopters avec qui on maintiendra une relation
  privilégiée pour continuer d'évangéliser en interne" (via [[https://twitter.com/looking4poetry/status/1284118404950110208][Twitter]])

- "Imposer que toutes les applications professionnelles soient au
  moins compatibles tout système d'exploitation (à défaut d'être
  libre, elles pourraient tourner avec GNU/Linux)" (via [[https://twitter.com/thom_karum/status/1284190110783864833][Twitter]]).

- "Créer une école d'état pour développeurs comme cela se fait dans
  d'autres métiers (agriculture, architecture) avec des études
  financées si contrat dans le public pendant une période." (via
  [[https://twitter.com/paulsouche/status/1286208386443485190][Twitter]]).

